### ISSUE TITLE
Crashing when loading scripts

### ISSUE THREAD

**Issue by GladieUO** [cbnolok/Leviathan#1]
It is always crash when loading scripts.
[![Screenshot from Gyazo](https://gyazo.com/2c58240f85760d5c217fe603f016e668/raw)](https://gyazo.com/2c58240f85760d5c217fe603f016e668)

**Comment by cbnolok** [comment]
Is it still giving problems?

**Comment by GladieUO** [comment]
still same :( i didnt wanted to told you, im the only one so :-D

**Comment by dnashard** [comment]
Same for me :-(

**Comment by GladieUO** [comment]
Fixed by Drk

**Comment by Jhobean** [comment]
Fix by commenting the faulty item.https://github.com/cbnolok/SphereX-Scriptpack/commit/42680cccc5c0e45909ba0b17a3699933fed1bfa6 

Itemdef 044CA
