### ISSUE TITLE
OSX Compilation error

### ISSUE THREAD

**Issue by Nirad** [cbnolok/Leviathan#2]
`:-1:error : unsupported option '-fopenmp'`

**Comment by cbnolok** [comment]
Which compiler?

**Comment by Nirad** [comment]
clang

**Comment by cbnolok** [comment]
It should work now

**Comment by Nirad** [comment]
i will test it thx

**Comment by Nirad** [comment]
`warning: unknown warning option '-Wmisleading-indentation'; did you mean '-Wbinding-in-condition'? [-Wunknown-warning-option]
../src/keystrokesender/keystrokesender_linux.cpp:9:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^~~~~~~~~~~~
1 warning and 1 error generated.
make: *** [keystrokesender_linux.o] Error 1
make: *** Waiting for unfinished jobs....
1 warning generated.
1 warning generated.
1 warning generated.
17:57:54: Le processus "/usr/bin/make" s'est terminé avec le code 2.
Erreur lors de la compilation/déploiement du projet Leviathan (kit : Desktop Qt 5.12.0 clang 64bit)
When executing step "Make"`

**Comment by Nirad** [comment]
i will try to work around this if you have hint I think the program think OSX is linux because it's unix based and in related  with the KeystrokeSender_linux

**Comment by cbnolok** [comment]
Yup at the time i didn't even think about someone compiling on a mac, so i just assumed that #ifndef _WIN32 was Linux. In the keystrokesender folder there are some preprocessor macros like that, i'd change them to #if defined(_WIN32) ... #elif defined(__unix__) &&!defined(__APPLE__). If you wish you can try to change that, in any case tomorrow i'm going to fix this, thanks for the report!

**Comment by Nirad** [comment]
Since CrossUO work very well in OSX I will be cool to have a tool like this for our Sphere server !
i will try to fix it thx for the quick reply

**Comment by Nirad** [comment]
Undefined symbols for architecture x86_64:
  "_compress2", referenced from:
      uopp::UOPFile::compressAndReplaceData(std::__1::vector<char, std::__1::allocator<char> > const*, uopp::CompressionFlag, bool, uopp::UOPError*) in uopfile.o
  "_compressBound", referenced from:
      uopp::UOPFile::compressAndReplaceData(std::__1::vector<char, std::__1::allocator<char> > const*, uopp::CompressionFlag, bool, uopp::UOPError*) in uopfile.o
  "_uncompress", referenced from:
      uopp::UOPFile::unpack(std::__1::vector<char, std::__1::allocator<char> >*, uopp::UOPError*) in uopfile.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Leviathan.app/Contents/MacOS/Leviathan] Error 1
19:44:55: Le processus "/usr/bin/make" s'est terminé avec le code 2.
Erreur lors de la compilation/déploiement du projet Leviathan (kit : Desktop Qt 5.12.0 clang 64bit)
When executing step "Make"

**Comment by cbnolok** [comment]
Looks like the linker couldn't find the 64 bits zlib library in your system. I'll do some research but maybe you'll come up with a solution faster since i've no experience with osx

**Comment by cbnolok** [comment]
Are you compiling under command line (using qmake and make) or under qt creator or xcode?

**Comment by Nirad** [comment]
I use qt creator to compile it

**Comment by cbnolok** [comment]
Do you have libz.dylib or zlib.dylib in your system?
If not: try running `brew install zlib`
Otherwise: find its path and add it in the .pro file:
```
# linux and mac
unix:!win32 {
    !mac {
        LIBS += -lz -L/usr/X11R6/lib -lX11      # dynamically link zlib and xlib (the latter for KeystrokeSender)

        QMAKE_CXXFLAGS += -fopenmp              # enable OpenMP pragmas as default flag for Linux
        LIBS += -fopenmp                        # link against OpenMP library
    } else {
HERE:        LIBS += -L/usr/lib(or /opt/lib?) -lz                             # dynamically link zlib
    }

    # disable some specific warnings
    QMAKE_CXXFLAGS += -Wno-implicit-fallthrough
    QMAKE_CXXFLAGS += -Wmisleading-indentation #-Wno-unknown-pragmas
}
```

**Comment by Nirad** [comment]
ok i have installed zlib to brew but I will try to compile again but I still have issue with keystroke Linux thing I give you news 

![Capture d’écran 2019-04-11 à 12 31 53](https://user-images.githubusercontent.com/359353/55974534-d52d4480-5c55-11e9-9941-36bc2b04dbe1.png)

witch one I link ? LDF or CPPF

**Comment by Nirad** [comment]
libz.dylib is in `/usr/lib` the one come with OSX

**Comment by cbnolok** [comment]
I'll push a commit in minutes trying to fix those errors, let's see

Il gio 11 apr 2019, 18:37 John <notifications@github.com> ha scritto:

**Comment by Nirad** [comment]
no keystroke off course but it's alive :)
![Capture d’écran 2019-04-11 à 12 46 40](https://user-images.githubusercontent.com/359353/55975411-e8411400-5c57-11e9-8882-847e0e515b83.png)

**Comment by Nirad** [comment]
not keystroke off course but it's alive :)

**Comment by cbnolok** [comment]
That's nice! Would you like to send a pull request to fix the compilation issues? Otherwise i'll try work on it

**Comment by Nirad** [comment]
![Capture d’écran 2019-04-11 à 12 49 53](https://user-images.githubusercontent.com/359353/55975597-55ed4000-5c58-11e9-9418-d7aac5a64b46.png)

**Comment by Nirad** [comment]
![Capture d’écran 2019-04-11 à 12 49 53](https://user-images.githubusercontent.com/359353/55975597-55ed4000-5c58-11e9-9418-d7aac5a64b46.png)

**Comment by Nirad** [comment]
i have hacked and commented all the key stroke thing I need to find the real way to do it

**Comment by Nirad** [comment]
```
# linux and mac
unix:!win32 {
    ##LIBS += -lz -L/usr/X11R6/lib -lX11      # dynamically link zlib and xlib (the latter for KeystrokeSender)

    # MAC section commented because it's UNTESTED
    #mac {
        # looks like OpenMP support here began only with recent LLVM versions?
        #  (Apple's LLVM versions have a different numeration from the official LLVM branch)
        #LLVMVER = system(g++ -x c++ -dM -E - < /dev/null | grep -Eo "__apple_build_version__  [0-9]{1,7}" | grep -Eo "[0-9]{1,7}")
        # OpenMP support began with "standard" version 3.8.0, which may be Apple 703.0.29 or 703.0.31. To be sure, check for 3.9.0 (>= Apple 800.0.38 ?)
        #greaterThan(LLVMVER, 80000037) {
        #    QMAKE_CXXFLAGS += -fopenmp              # enable OpenMP pragmas
        #    # or should we use -fopenmp=libomp ?
        #    #LIBS += -fopenmp
        #} else {
            ##QMAKE_CXXFLAGS += -fopenmp     # no openmp for you
            ##LIBS += -fopenmp
        #}
    #}
    !mac {
        QMAKE_CXXFLAGS += -fopenmp              # enable OpenMP pragmas as default flag for Linux
        LIBS += -fopenmp    # link against OpenMP library
    } else {
        LIBS += -L/usr/lib -lz                             # dynamically link zlib
    }

    # disable some specific warnings
    QMAKE_CXXFLAGS += -Wno-implicit-fallthrough
    QMAKE_CXXFLAGS += -Wmisleading-indentation #-Wno-unknown-pragmas

}

**Comment by cbnolok** [comment]
Okay i'll try to make it work cleanly then!

**Comment by Nirad** [comment]
Thx for sure we need if OSX or Mac in the code I need to go but I keep an eyes on this Thx for your work ! to separate unix thing

**Comment by Nirad** [comment]
[compileout.txt](https://github.com/cbnolok/Leviathan/files/3073420/compileout.txt)

**Comment by Nirad** [comment]
ok I think it's just how the if platform specific work I will try to fix it and push a PR thx

**Comment by cbnolok** [comment]
Can it be that on OSX `__unix__` isn't defined?

**Comment by Nirad** [comment]
Check this way it's work !

**Comment by Nirad** [comment]
my pr is ready and this way we can even catch win64

**Comment by cbnolok** [comment]
So it was only a macro problem, probably __unix__ missing, good to know! Tbh i prefer to rely on the .pro and qmake the least i can, so that the code is as much "copy-pastable" as possible, even for projects not using qt, so I'd like to fix it by changing the #if defined instructions. Thanks for the pr though! It was useful to learn what was wrong (btw _WIN32, as much counterintuitive it is, is defined also in a 64 bits env)
